services:
  app:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - /home/float/files:/app/src/files
    command: >
      sh -c "mkdir -p /home/float/files && python main.py"
